CREATE TABLE comment (
  id CHAR(36) NOT NULL PRIMARY KEY,
 	blog_id CHAR(36) NOT NULL,
	content TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Foreign Key (blog_id) REFERENCES blogs(id) ON UPDATE CASCADE ON DELETE CASCADE
);