CREATE TABLE links (
  id CHAR(36) NOT NULL PRIMARY KEY,
  blog_id CHAR(36) NOT NULL,
	rel VARCHAR(100) NOT NULL,
	href VARCHAR(500) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (blog_id) REFERENCES blogs(id) ON UPDATE CASCADE ON DELETE CASCADE
);